import { useState, useEffect } from 'react';
import { getSimulationRepositories, generateScripts } from '../api/queryApi';
import type { ScriptRepository, ScriptGenerationRequest } from '../api/queryApi';
import './ScriptGeneratorModal.css';

interface ScriptGeneratorModalProps {
  sql: string;
  estimatedAffectedRows: number | null;
  onClose: () => void;
}

export default function ScriptGeneratorModal({
  sql,
  estimatedAffectedRows,
  onClose,
}: ScriptGeneratorModalProps) {
  const [repositories, setRepositories] = useState<ScriptRepository[]>([]);
  const [loadingRepos, setLoadingRepos] = useState(true);
  const [repositoryKey, setRepositoryKey] = useState('');
  const [workItemId, setWorkItemId] = useState<number | ''>('');
  const [purpose, setPurpose] = useState('');
  const [expectedRows, setExpectedRows] = useState<number | ''>(
    estimatedAffectedRows ?? ''
  );
  const [databaseName, setDatabaseName] = useState('');
  const [creating, setCreating] = useState(false);
  const [result, setResult] = useState<{ success: boolean; message: string } | null>(null);

  useEffect(() => {
    async function loadRepositories() {
      try {
        const repos = await getSimulationRepositories();
        setRepositories(repos);
        if (repos.length > 0) {
          setRepositoryKey(repos[0].key);
        }
      } catch (err) {
        console.error('Failed to load repositories:', err);
      } finally {
        setLoadingRepos(false);
      }
    }
    loadRepositories();
  }, []);

  const generateQuerySqlPreview = (): string => {
    const rows = typeof expectedRows === 'number' ? expectedRows : 0;
    return `DECLARE @expectedAffectedRowCount INT = ${rows};
-- Verification query showing rows that will be affected
-- TODO: Add a SELECT query that returns the rows matching your UPDATE/DELETE criteria
SELECT @expectedAffectedRowCount AS ExpectedAffectedRowCount;`;
  };

  const generateUpdateSqlPreview = (): string => {
    const rows = typeof expectedRows === 'number' ? expectedRows : 0;
    const db = databaseName.trim() || 'Unknown';
    const timestamp = new Date().toISOString();
    const workItem = typeof workItemId === 'number' ? workItemId : 0;
    const desc = purpose.trim() || 'No description provided';

    return `-- Data Fix Script for Work Item #${workItem}
-- Purpose: ${desc}
-- Generated: ${timestamp}
-- Generated By: SQL Audited Query Tool
-- Database: ${db}
-- Estimated Affected Rows: ${rows}

${sql}

SELECT @@ROWCOUNT AS ActualRowsAffected;`;
  };

  const handleCreateFiles = async () => {
    if (typeof workItemId !== 'number' || typeof expectedRows !== 'number') {
      setResult({ success: false, message: 'Work Item ID and Expected Affected Rows are required' });
      return;
    }

    setCreating(true);
    setResult(null);

    try {
      const request: ScriptGenerationRequest = {
        sql,
        repositoryKey,
        workItemId,
        purpose: purpose.trim(),
        expectedAffectedRows: expectedRows,
        databaseName: databaseName.trim() || null,
      };

      const response = await generateScripts(request);
      
      if (response.succeeded) {
        setResult({
          success: true,
          message: `Files created successfully in ${response.outputDirectory}`,
        });
      } else {
        setResult({
          success: false,
          message: response.errorMessage || 'Failed to create files',
        });
      }
    } catch (err) {
      setResult({
        success: false,
        message: err instanceof Error ? err.message : 'Failed to create files',
      });
    } finally {
      setCreating(false);
    }
  };

  const handleCopyToClipboard = () => {
    const querySql = generateQuerySqlPreview();
    const updateSql = generateUpdateSqlPreview();
    const combined = `--- query.sql ---\n${querySql}\n\n--- update.sql ---\n${updateSql}`;
    
    navigator.clipboard.writeText(combined).then(() => {
      setResult({ success: true, message: 'Copied to clipboard!' });
    }).catch(() => {
      setResult({ success: false, message: 'Failed to copy to clipboard' });
    });
  };

  return (
    <div className="script-modal-overlay" onClick={onClose}>
      <div className="script-modal" onClick={(e) => e.stopPropagation()}>
        <div className="script-modal-header">
          <h2>Generate sql-script-runner Scripts</h2>
          <button className="script-modal-close" onClick={onClose}>
            ✕
          </button>
        </div>

        <div className="script-modal-body">
          <div className="script-modal-form">
            <div className="script-modal-field">
              <label htmlFor="repository">Sql Patches Repo</label>
              {loadingRepos ? (
                <div className="script-modal-loading">Loading repositories...</div>
              ) : repositories.length === 0 ? (
                <div className="script-modal-error">No repositories configured</div>
              ) : (
                <select
                  id="repository"
                  value={repositoryKey}
                  onChange={(e) => setRepositoryKey(e.target.value)}
                >
                  {repositories.map((repo) => (
                    <option key={repo.key} value={repo.key}>
                      {repo.name}
                    </option>
                  ))}
                </select>
              )}
            </div>

            <div className="script-modal-field">
              <label htmlFor="workItemId">Work Item ID *</label>
              <input
                id="workItemId"
                type="number"
                min="1"
                value={workItemId}
                onChange={(e) => {
                  const val = e.target.value;
                  setWorkItemId(val === '' ? '' : parseInt(val, 10));
                }}
                placeholder="e.g., 12345"
              />
            </div>

            <div className="script-modal-field">
              <label htmlFor="purpose">Purpose/Description *</label>
              <textarea
                id="purpose"
                rows={3}
                value={purpose}
                onChange={(e) => setPurpose(e.target.value)}
                placeholder="Describe the fix being applied..."
              />
            </div>

            <div className="script-modal-field">
              <label htmlFor="expectedRows">Expected Affected Rows *</label>
              <input
                id="expectedRows"
                type="number"
                min="0"
                value={expectedRows}
                onChange={(e) => {
                  const val = e.target.value;
                  setExpectedRows(val === '' ? '' : parseInt(val, 10));
                }}
              />
            </div>

            <div className="script-modal-field">
              <label htmlFor="database">Database Name</label>
              <input
                id="database"
                type="text"
                value={databaseName}
                onChange={(e) => setDatabaseName(e.target.value)}
                placeholder="e.g., ProductionDB (optional)"
              />
            </div>
          </div>

          <div className="script-modal-preview">
            <h3>query.sql Preview</h3>
            <pre className="script-modal-code">{generateQuerySqlPreview()}</pre>

            <h3>update.sql Preview</h3>
            <pre className="script-modal-code">{generateUpdateSqlPreview()}</pre>
          </div>

          {result && (
            <div
              className={`script-modal-result ${result.success ? 'script-modal-result--success' : 'script-modal-result--error'}`}
            >
              {result.message}
            </div>
          )}
        </div>

        <div className="script-modal-footer">
          <button
            className="script-modal-btn script-modal-btn--secondary"
            onClick={onClose}
          >
            Cancel
          </button>
          <button
            className="script-modal-btn script-modal-btn--secondary"
            onClick={handleCopyToClipboard}
          >
            📋 Copy to Clipboard
          </button>
          <button
            className="script-modal-btn script-modal-btn--primary"
            onClick={handleCreateFiles}
            disabled={creating || !repositoryKey || typeof workItemId !== 'number' || typeof expectedRows !== 'number'}
          >
            {creating ? '⏳ Creating...' : '✅ Create Files'}
          </button>
        </div>
      </div>
    </div>
  );
}
