using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using SqlAuditedQueryTool.Core.Interfaces;
using SqlAuditedQueryTool.Core.Models;

namespace SqlAuditedQueryTool.Database;

/// <summary>
/// Service for generating sql-script-runner scripts for work items.
/// </summary>
public sealed class ScriptGeneratorService : IScriptGeneratorService
{
    private readonly SqlScriptRunnerOptions _options;
    private readonly ILogger<ScriptGeneratorService> _logger;

    public ScriptGeneratorService(IOptions<SqlScriptRunnerOptions> options, ILogger<ScriptGeneratorService> logger)
    {
        _options = options.Value;
        _logger = logger;
    }

    public ScriptGenerationResult GenerateScripts(ScriptGenerationRequest request)
    {
        try
        {
            // Validate repository key exists
            if (!_options.Repositories.TryGetValue(request.RepositoryKey, out var repoName))
            {
                return new ScriptGenerationResult
                {
                    Succeeded = false,
                    ErrorMessage = $"Repository key '{request.RepositoryKey}' not found in configuration."
                };
            }

            // Resolve repository directory
            var repoDirectory = Path.Combine(_options.ReposBaseDirectory, repoName);
            if (!Directory.Exists(repoDirectory))
            {
                return new ScriptGenerationResult
                {
                    Succeeded = false,
                    ErrorMessage = $"Repository directory not found: {repoDirectory}"
                };
            }

            // Create SqlPatches/{WorkItemId} directory
            var outputDirectory = Path.Combine(repoDirectory, "SqlPatches", request.WorkItemId.ToString());
            Directory.CreateDirectory(outputDirectory);

            // Generate query.sql content
            var querySqlContent = $@"DECLARE @expectedAffectedRowCount INT = {request.ExpectedAffectedRows};
-- Verification query showing rows that will be affected
-- TODO: Add a SELECT query that returns the rows matching your UPDATE/DELETE criteria
SELECT @expectedAffectedRowCount AS ExpectedAffectedRowCount;
";

            // Generate update.sql content
            var timestamp = DateTimeOffset.UtcNow.ToString("o");
            var requestedBy = request.RequestedBy ?? "SQL Audited Query Tool";
            var databaseName = request.DatabaseName ?? "Unknown";
            
            var updateSqlContent = $@"-- Data Fix Script for Work Item #{request.WorkItemId}
-- Purpose: {request.Purpose}
-- Generated: {timestamp}
-- Generated By: {requestedBy}
-- Database: {databaseName}
-- Estimated Affected Rows: {request.ExpectedAffectedRows}

{request.Sql}

SELECT @@ROWCOUNT AS ActualRowsAffected;
";

            // Write files
            var querySqlPath = Path.Combine(outputDirectory, "query.sql");
            var updateSqlPath = Path.Combine(outputDirectory, "update.sql");

            File.WriteAllText(querySqlPath, querySqlContent);
            File.WriteAllText(updateSqlPath, updateSqlContent);

            _logger.LogInformation("Generated sql-script-runner scripts in {OutputDirectory}", outputDirectory);

            return new ScriptGenerationResult
            {
                Succeeded = true,
                QuerySqlContent = querySqlContent,
                UpdateSqlContent = updateSqlContent,
                OutputDirectory = outputDirectory,
                FilesCreated = true
            };
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to generate scripts");
            return new ScriptGenerationResult
            {
                Succeeded = false,
                ErrorMessage = ex.Message
            };
        }
    }
}
